### PR TITLE
Update to v24 and add pamac addition

### PR DESCRIPTION
**Pull request by Ste74**
;)

### CODE REVIEW

**Comment by Ste74** [comment]
Well is in unstable .. check it .. i think we can remove the pamac updater added by @fhdk because in  my hands open always the pamac-manager :p

**Comment by fhdk** [comment]
I think the regent chances to pamac had done influence. I have had random opening og Winther despoten I used the appropriate versions -manager and -updater. Maybe the updater is missing a shell var?

⁣Sendt af Blue ​from my phone

Den 15. okt. 2017 22.15, fra 22.15, Stefano Capitani <notifications@github.com> skrev:

**Comment by Ste74** [comment]
Hi @fhdk , i have removed for now this entry since the two script of @Chrysostomus work fine to check and open the update manager
https://github.com/Chrysostomus/arch-update/pull/3/commits/76809981e15436b927284acbdbc59d2c025755b8#diff-06f1274e40de25abda72d812b1cce86aR60

**Comment by fhdk** [comment]
:+1: I think I made the additions to the menu due to a user request - but if it is not optimal its ok by me.

Currently I am experimenting heavily with openbox now mostly due to keyb centric way and very much due to the tiling features which I have grown very dependent on.

My ultimate goal is to revive the openbox community edition with an iso preferably below 1GB :smile_cat:

**Comment by Ste74** [comment]
Good work btw :D ... users love openbox .. cross the fingers ;)

**Pull request merged**
